# Generated by Django 3.1.5 on 2021-01-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('P_id', models.AutoField(primary_key=True, serialize=False)),
                ('P_image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
