# Generated by Django 3.1.5 on 2021-02-01 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlpannel', '0002_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='P_description',
            field=models.CharField(default='temp', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='P_name',
            field=models.CharField(default='temp', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='P_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='P_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controlpannel.categories'),
        ),
    ]
