# Generated by Django 3.1.5 on 2021-02-01 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpannel', '0003_auto_20210201_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 1, 16, 0, 51, 3954), null=True),
        ),
    ]
