# Generated by Django 3.1.5 on 2021-02-01 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpannel', '0004_comments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 1, 19, 17, 14, 545)),
        ),
    ]
