# Generated by Django 3.1.5 on 2021-02-01 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpannel', '0005_auto_20210201_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 1, 19, 18, 38, 388700)),
        ),
    ]
