# Generated by Django 3.1.5 on 2021-02-02 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpannel', '0007_auto_20210202_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 2, 9, 41, 15, 570120)),
        ),
    ]
